### ISSUE TITLE
Permalink to topcat search results through URL

### ISSUE THREAD

**Issue by GMDuncan** [jncc/topcat#262] opened 2017-12-22 10:24 UTC
For some datasets, groups of sibling metadata are linked by a specific value in a vocabulary. For example, marine survey datasets and the "seabed-survey-cruise-id" value.

It would be useful to be able to use this to provide a link/URL to sets of metadata.
For example:
http://topcat/app/#/?f.keywords=vocab.jncc.gov.uk%2Fseabed-survey-cruise-id%2F1714S
would arrive at the same page as someone searching TopCat for 1714S (keyword)

Currently, topcat doesn't recognise the querystring and following the link above lands at the homepage.

**Comment by LynnHeeley** [comment] 2019-07-31 08:30
effective duplicate of #276

**Closed by LynnHeeley** 2019-07-31 08:30 UTC
